package com.martin.ads.vrlib.filters.advanced;

/**
 * Created by Ads on 2017/2/13.
 */

public enum FilterType {
    NONE,
    FILL_LIGHT_FILTER,
    GREEN_HOUSE_FILTER,
    BLACK_WHITE_FILTER,
    PAST_TIME_FILTER,
    MOON_LIGHT_FILTER,
    PRINTING_FILTER,
    TOY_FILTER,
    BRIGHTNESS_FILTER,
    VIGNETTE_FILTER,
    MULTIPLY_FILTER,
    REMINISCENCE_FILTER,
    SUNNY_FILTER,
    MX_LOMO_FILTER,
    SHIFT_COLOR_FILTER,
    MX_FACE_BEAUTY_FILTER,
    MX_PRO_FILTER,
}
